# Generated by Django 5.0.1 on 2024-01-11 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("flashcards", "0001_initial"),
        ("flashcards", "0002_answer_author_answer_pub_date_and_more"),
        (
            "flashcards",
            "0003_answer_language_question_author_question_language_and_more",
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("author", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("EN", "English"), ("RU", "Russian")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=500)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flashcards.question",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=30, null=True)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("EN", "English"), ("RU", "Russian")],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
